import java.io.*;

public class Prueba {
  static String inst[] = new String[10000];

  public static void main(String[] args) {
      inst[0] = "mete 4";
      inst[1] = "mete 0";
      inst[2] = "asig";
      inst[3] = "mete Dame coeficiente A: ";
      inst[4] = "escribe";
      inst[5] = "mete 9";
      inst[6] = "lee";
      inst[7] = "asig";
      inst[8] = "mete Dame coeficiente B: ";
      inst[9] = "escribe";
      inst[10] = "mete 8";
      inst[11] = "lee";
      inst[12] = "asig";
      inst[13] = "mete Dame coeficiente C: ";
      inst[14] = "escribe";
      inst[15] = "mete 10";
      inst[16] = "lee";
      inst[17] = "asig";
      inst[18] = "mete Ingresa tu nombre: ";
      inst[19] = "escribe";
      inst[20] = "mete 11";
      inst[21] = "lee";
      inst[22] = "asig";
      inst[23] = "mete 0";
      inst[24] = "mete 5";
      inst[25] = "mete 2";
      inst[26] = "mem";
      inst[27] = "mete 2";
      inst[28] = "mem";
      inst[29] = "opmul";
      inst[30] = "mete 4";
      inst[31] = "mete 1";
      inst[32] = "mem";
      inst[33] = "opmul";
      inst[34] = "mete 3";
      inst[35] = "mem";
      inst[36] = "opmul";
      inst[37] = "opdif";
      inst[38] = "asig";
      inst[39] = "opdif";
      inst[40] = "copia";
      inst[41] = "opabs";
      inst[42] = "opsum";
      inst[43] = "mete 49";
      inst[44] = "irverdad";
      inst[45] = "mete La ecuacion tiene raices reales";
      inst[46] = "escribenl";
      inst[47] = "mete 51";
      inst[48] = "ira";
      inst[49] = "mete La ecuacion tiene raices complejas";
      inst[50] = "escribenl";
      inst[51] = "copia";
      inst[52] = "saca";
      inst[53] = "mete El valor del discriminante es: ";
      inst[54] = "escribe";
      inst[55] = "mete 5";
      inst[56] = "mem";
      inst[57] = "escribe";
      inst[58] = "mete Adios";
      inst[59] = "escribenl";
      inst[60] = "mete 4";
      inst[61] = "mete 4";
      inst[62] = "mem";
      inst[63] = "mete 1";
      inst[64] = "opsum";
      inst[65] = "asig";
      inst[66] = "mete 4";
      inst[67] = "mem";
      inst[68] = "mete 10";
      inst[69] = "opdif";
      inst[70] = "copia";
      inst[71] = "opabs";
      inst[72] = "opsum";
      inst[73] = "mete 58";
      inst[74] = "irfalso";
      inst[75] = "fin";
      MaqCAPJava.programa(inst, args);
  }
}
